In [1]:
import pandas as pd 
import numpy as np 

print("elweli")

elweli

In [2]:
import pandas as pd

path = "../data/student-mat.csv"

df = pd.read_csv(path, sep=";")

df.head()

  school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0  GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mot...
1  GP,F,17,U,GT3,T,1,1,at_home,other,course,fathe...
2  GP,F,15,U,LE3,T,1,1,at_home,other,other,mother...
3  GP,F,15,U,GT3,T,4,2,health,services,home,mothe...
4  GP,F,16,U,GT3,T,3,3,other,other,home,father,1,...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                               Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                               --------------  -----
 0   school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3  395 non-null    object
dtypes: object(1)
memory usage: 3.2+ KB

In [4]:
df = pd.read_csv(path, sep=",")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [6]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [7]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [8]:
import pandas as pd
import os

In [9]:
# --- Définir les chemins ---
csv_path = os.path.join("..", "data", "movies_metadata.csv")
excel_path = os.path.join("..", "data", "gestion.xlsx")
json_path = os.path.join("..", "data", "movies_metadata.json")

In [10]:
# --- Lecture du CSV ---
df_movies = pd.read_csv(csv_path)
print("🎬 Données Movies CSV (5 premières lignes):")
print(df_movies.head())
print("\nInformations sur les colonnes:")
print(df_movies.info())

🎬 Données Movies CSV (5 premières lignes):
   adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1  False                                                NaN  65000000
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3  False                                                NaN  16000000
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                     [{'id': 35, 'name': 'Comedy'}]

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en
1                                   NaN   8844  tt0113497                en
2                                   NaN  15602  tt0113228                en
3                                   NaN  31357  tt0114885                en
4                                   NaN  11862  tt0113041                en

                original_title  \
0                    Toy Story
1                      Jumanji
2             Grumpier Old Men
3            Waiting to Exhale
4  Father of the Bride Part II

                                            overview  ... release_date  \
0  Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30
1  When siblings Judy and Peter discover an encha...  ...   1995-12-15
2  A family wedding reignites the ancient feud be...  ...   1995-12-22
3  Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22
4  Just when George Banks has recovered from his ...  ...   1995-02-10

       revenue runtime                                   spoken_languages  \
0  373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]
1  262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2          0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]
3   81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]
4   76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]

     status                                            tagline  \
0  Released                                                NaN
1  Released          Roll the dice and unleash the excitement!
2  Released  Still Yelling. Still Fighting. Still Ready for...
3  Released  Friends are the people who let you be yourself...
4  Released  Just When His World Is Back To Normal... He's ...

                         title  video vote_average vote_count
0                    Toy Story  False          7.7     5415.0
1                      Jumanji  False          6.9     2413.0
2             Grumpier Old Men  False          6.5       92.0
3            Waiting to Exhale  False          6.1       34.0
4  Father of the Bride Part II  False          5.7      173.0

[5 rows x 24 columns]

Informations sur les colonnes:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB
None

/var/folders/0n/c62vy7y16bb7jf6538hsyjlm0000gn/T/ipykernel_53393/4222760853.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_movies = pd.read_csv(csv_path)

In [ ]:
# --- Conversion CSV -> JSON Lines ---
df_movies.to_json(json_path, orient="records", lines=True, force_ascii=False)
print(f"\n Fichier JSON créé: {json_path}")

✅ Fichier JSON créé: ../data/movies_metadata.json

In [12]:
# --- Lecture du fichier Excel ---
df_excel = pd.read_excel(excel_path, sheet_name="Feuille1")
print("\n Données Excel (5 premières lignes):")
print(df_excel.head())

FileNotFoundError: [Errno 2] No such file or directory: '../data/gestion.xlsx'

In [13]:
# --- Lecture du fichier Excel ---
df_excel = pd.read_excel(excel_path, sheet_name="Feuille1")
print("\n Données Excel (5 premières lignes):")
print(df_excel.head())

FileNotFoundError: [Errno 2] No such file or directory: '../data/gestion.xlsx'

In [14]:
# --- Lecture du fichier Excel ---
df_excel = pd.read_excel(excel_path, sheet_name="Feuille1")
print("\n Données Excel (5 premières lignes):")
print(df_excel.head())

ValueError: Worksheet named 'Feuille1' not found

In [15]:
# --- Lecture du fichier Excel ---
df_excel = pd.read_excel(excel_path, sheet_name="Feuille1")
print("\n Données Excel (5 premières lignes):")
print(df_excel.head())

FileNotFoundError: [Errno 2] No such file or directory: '../data/gestion.xlsx'

In [16]:
# --- Lecture du fichier Excel ---
df_excel = pd.read_excel(excel_path, sheet_name="Feuille1")
print("\n Données Excel (5 premières lignes):")
print(df_excel.head())

ValueError: Worksheet named 'Feuille1' not found

In [17]:
# --- Lecture du fichier Excel ---
df_excel = pd.read_excel(excel_path, sheet_name="Feuille1")
print("\n Données Excel (5 premières lignes):")
print(df_excel.head())

 Données Excel (5 premières lignes):
   Unnamed: 0                                         Unnamed: 1  \
0         NaN  Sample Excel File with Employee Data for Practice
1         NaN                                                NaN
2         NaN                                               Name
3         NaN                                               Mark
4         NaN                                              Brian

            Unnamed: 2     Unnamed: 3  Unnamed: 4      Unnamed: 5  Unnamed: 6
0                  NaN            NaN         NaN             NaN         NaN
1                  NaN            NaN         NaN             NaN         NaN
2         Joining Date  Email Address  Department  Monthly Salary  Job Status
3  2021-12-31 00:00:00            NaN         NaN             NaN         NaN
4  2021-12-31 00:00:00            NaN         NaN             NaN         NaN

In [18]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
"mysql+pymysql://root:password@localhost/school"
)

query = "SELECT * FROM etudiants WHERE G3 > 15"

df_students = pd.read_sql(query, engine)

print(df_students.head())

ModuleNotFoundError: No module named 'sqlalchemy'

In [19]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
"mysql+pymysql://root:password@localhost/school"
)

query = "SELECT * FROM etudiants WHERE G3 > 15"

df_students = pd.read_sql(query, engine)

print(df_students.head())

OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [20]:
from sqlalchemy import create_engine
import pandas as pd

# افترض كلمة المرور فارغة
engine = create_engine(
    "mysql+pymysql://root:@localhost:8080/school"  # ← لاحظ ":8080"
)

query = "SELECT * FROM etudiants WHERE G3 > 15"

df_students = pd.read_sql(query, engine)
print(df_students.head())

OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [21]:
from sqlalchemy import create_engine
import pandas as pd

# افترض كلمة المرور فارغة
engine = create_engine(
    "mysql+pymysql://root:@localhost:8080/school"  # ← لاحظ ":8080"
)

query = "SELECT * FROM etudiants WHERE G3 > 15"

df_students = pd.read_sql(query, engine)
print(df_students.head())

OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [22]:
from sqlalchemy import create_engine
import pandas as pd

# افترض كلمة المرور فارغة
engine = create_engine(
    "mysql+pymysql://root:@localhost:8080/school"  # ← لاحظ ":8080"
)

query = "SELECT * FROM etudiants WHERE G3 > 15"

df_students = pd.read_sql(query, engine)
print(df_students.head())

OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [23]:
from sqlalchemy import create_engine
import pandas as pd

# افترض كلمة المرور فارغة
engine = create_engine(
    "mysql+pymysql://root:@localhost:3306/school"  # ← 3306"
)

query = "SELECT * FROM etudiants WHERE G3 > 15"

df_students = pd.read_sql(query, engine)
print(df_students.head())

OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'G3' in 'where clause'")
[SQL: SELECT * FROM etudiants WHERE G3 > 15]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [24]:
from sqlalchemy import create_engine
import pandas as pd

# افترض كلمة المرور فارغة
engine = create_engine(
    "mysql+pymysql://root:@localhost:3306/school"  # ← 3306"
)

query = "SELECT * FROM etudiants WHERE G3 > 15"

df_students = pd.read_sql(query, engine)
print(df_students.head())

   StudentID school sex  age  G1  G2  G3
0          3     GP   F   15  14  15  16
1          4     GP   M   16  15  16  17
2          5     GP   F   17  16  17  18
3         10     GP   M   17  14  15  16
4         13     GP   F   15  14  15  16

In [25]:

import requests

robots = requests.get("https://example.com/robots.txt")
print(robots.text)

SSLError: HTTPSConnectionPool(host='example.com', port=443): Max retries exceeded with url: /robots.txt (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1017)')))

In [26]:
import requests

robots = requests.get("https://example.com/robots.txt")
print(robots.text)

SSLError: HTTPSConnectionPool(host='example.com', port=443): Max retries exceeded with url: /robots.txt (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1017)')))

In [ ]:
import requests
import urllib3
from bs4 import BeautifulSoup
import pandas as pd

# ----------------------------------------
#  تعطيل تحذيرات SSL على Mac
# ----------------------------------------
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# ----------------------------------------
#  التحقق من robots.txt لموقع حقيقي
# ----------------------------------------
robots_url = "https://www.bbc.com/robots.txt"
robots_response = requests.get(robots_url, verify=False)  # تجاهل SSL مؤقتاً
print("Robots.txt:\n", robots_response.text[:500], "...")  # عرض أول 500 حرف فقط

# ----------------------------------------
#  Web Scraping - استخراج عناوين الأخبار
# ----------------------------------------
news_url = "https://www.bbc.com/news"
page = requests.get(news_url, verify=False)
soup = BeautifulSoup(page.content, "html.parser")

# استخراج العناوين داخل عناصر <h3>
titles = [h3.text.strip() for h3 in soup.find_all("h3")]
print(f"\nعدد العناوين المكتشفة: {len(titles)}")
print("أول 10 عناوين:", titles[:10])

# تحويل العناوين إلى DataFrame
df_web = pd.DataFrame(titles, columns=["News_Title"])


# استدعاء API وتحويله إلى DataFrame
# ----------------------------------------
api_url = "https://jsonplaceholder.typicode.com/posts"
response_api = requests.get(api_url)
data_json = response_api.json()

df_api = pd.DataFrame(data_json)
print("\nأول 5 صفوف من API:\n", df_api.head())

Robots.txt:

# version: 33da601c81953a45668bf5504fe0e8f8fb8aa953
# The BBC's Terms of Use: https://www.bbc.co.uk/terms
# - Explain the rules for using our services
# - Tell you what you can do with our content
#
# In short: Please use our site like a human, not a robot.
# That means:
# - No scraping, crawling, or systematic extraction of content
# - No use of BBC content for training or fine-tuning AI models, including large language models (LLMs)
# - No retrieval-augmented generation (RAG), AI-powered sea ...

عدد العناوين المكتشفة: 1
أول 10 عناوين: ['The BBC is in multiple languages']

أول 5 صفوف من API:
    userId  id                                              title  \
0       1   1  sunt aut facere repellat provident occaecati e...
1       1   2                                       qui est esse
2       1   3  ea molestias quasi exercitationem repellat qui...
3       1   4                               eum et est occaecati
4       1   5                                 nesciunt quas odio

                                                body
0  quia et suscipit\nsuscipit recusandae consequu...
1  est rerum tempore vitae\nsequi sint nihil repr...
2  et iusto sed quo iure\nvoluptatem occaecati om...
3  ullam et saepe reiciendis voluptatem adipisci\...
4  repudiandae veniam quaerat sunt sed\nalias aut...

In [ ]:

# ----------------------------------------
# 1️⃣ دمج بيانات CSV + SQL + Web Scraping + API
# ----------------------------------------
# افترض أن لديك df_top_students من تمرين MySQL
# واستورد CSV
df_csv = pd.read_csv("data/student-mat.csv")

# دمج CSV و SQL
df_csv_sql = pd.concat([df_csv, df_top_students], ignore_index=True)

# دمج مع Web Scraping
df_csv_sql_web = pd.concat([df_csv_sql.reset_index(drop=True), df_web.reset_index(drop=True)], axis=1)

# دمج مع API
df_final = pd.concat([df_csv_sql_web.reset_index(drop=True), df_api.reset_index(drop=True)], axis=1)

# معاينة البيانات المدمجة
print("\nأول 5 صفوف من DataFrame النهائي:\n", df_final.head())

FileNotFoundError: [Errno 2] No such file or directory: 'data/student-mat.csv'

In [ ]:

# ----------------------------------------
# 1️⃣ دمج بيانات CSV + SQL + Web Scraping + API
# ----------------------------------------
# افترض أن لديك df_top_students من تمرين MySQL
# واستورد CSV
df_csv = pd.read_csv("data/student-mat2.csv")

# دمج CSV و SQL
df_csv_sql = pd.concat([df_csv, df_top_students], ignore_index=True)

# دمج مع Web Scraping
df_csv_sql_web = pd.concat([df_csv_sql.reset_index(drop=True), df_web.reset_index(drop=True)], axis=1)

# دمج مع API
df_final = pd.concat([df_csv_sql_web.reset_index(drop=True), df_api.reset_index(drop=True)], axis=1)

# معاينة البيانات المدمجة
print("\nأول 5 صفوف من DataFrame النهائي:\n", df_final.head())

FileNotFoundError: [Errno 2] No such file or directory: 'data/student-mat.csv'

In [30]:

# ----------------------------------------
# 1️⃣ دمج بيانات CSV + SQL + Web Scraping + API
# ----------------------------------------
# افترض أن لديك df_top_students من تمرين MySQL
# واستورد CSV
df_csv = pd.read_csv("data/student-mat2.csv")

# دمج CSV و SQL
df_csv_sql = pd.concat([df_csv, df_top_students], ignore_index=True)

# دمج مع Web Scraping
df_csv_sql_web = pd.concat([df_csv_sql.reset_index(drop=True), df_web.reset_index(drop=True)], axis=1)

# دمج مع API
df_final = pd.concat([df_csv_sql_web.reset_index(drop=True), df_api.reset_index(drop=True)], axis=1)

# معاينة البيانات المدمجة
print("\nأول 5 صفوف من DataFrame النهائي:\n", df_final.head())

FileNotFoundError: [Errno 2] No such file or directory: 'data/student-mat2.csv'

In [31]:

# ----------------------------------------
# 1️⃣ دمج بيانات CSV + SQL + Web Scraping + API
# ----------------------------------------
# افترض أن لديك df_top_students من تمرين MySQL
# واستورد CSV
df_csv = pd.read_csv("data/student-mat 2.csv")

# دمج CSV و SQL
df_csv_sql = pd.concat([df_csv, df_top_students], ignore_index=True)

# دمج مع Web Scraping
df_csv_sql_web = pd.concat([df_csv_sql.reset_index(drop=True), df_web.reset_index(drop=True)], axis=1)

# دمج مع API
df_final = pd.concat([df_csv_sql_web.reset_index(drop=True), df_api.reset_index(drop=True)], axis=1)

# معاينة البيانات المدمجة
print("\nأول 5 صفوف من DataFrame النهائي:\n", df_final.head())

FileNotFoundError: [Errno 2] No such file or directory: 'data/student-mat 2.csv'

In [ ]:
import pandas as pd

# ----------------------------------------
# 1️⃣ قراءة CSV
# ----------------------------------------
df_csv = pd.read_csv("data/student-mat 2.csv")
print("أول 5 صفوف من CSV:\n", df_csv.head())

# ----------------------------------------
# 2️⃣ دمج مع Web Scraping
# افترض أن df_web موجود مسبقًا
# ----------------------------------------
df_csv_web = pd.concat([df_csv.reset_index(drop=True), df_web.reset_index(drop=True)], axis=1)

# ----------------------------------------
# 3️⃣ دمج مع API
# افترض أن df_api موجود مسبقًا
# ----------------------------------------
df_final = pd.concat([df_csv_web.reset_index(drop=True), df_api.reset_index(drop=True)], axis=1)

# ----------------------------------------
# 4️⃣ معاينة البيانات المدمجة
# ----------------------------------------
print("\nأول 5 صفوف من DataFrame النهائي:\n", df_final.head())

# ----------------------------------------
# 5️⃣ حفظ البيانات النهائية
# ----------------------------------------
df_final.to_csv("data/df_final.csv", index=False)
print("\nتم حفظ DataFrame النهائي في 'data/df_final.csv'")

FileNotFoundError: [Errno 2] No such file or directory: 'data/student-mat2.csv'

In [33]:
import pandas as pd

# ----------------------------------------
# 1️⃣ قراءة CSV
# ----------------------------------------
df_csv = pd.read_csv("data/student-mat 2.csv")
print("أول 5 صفوف من CSV:\n", df_csv.head())

# ----------------------------------------
# 2️⃣ دمج مع Web Scraping
# افترض أن df_web موجود مسبقًا
# ----------------------------------------
df_csv_web = pd.concat([df_csv.reset_index(drop=True), df_web.reset_index(drop=True)], axis=1)

# ----------------------------------------
# 3️⃣ دمج مع API
# افترض أن df_api موجود مسبقًا
# ----------------------------------------
df_final = pd.concat([df_csv_web.reset_index(drop=True), df_api.reset_index(drop=True)], axis=1)

# ----------------------------------------
# 4️⃣ معاينة البيانات المدمجة
# ----------------------------------------
print("\nأول 5 صفوف من DataFrame النهائي:\n", df_final.head())

# ----------------------------------------
# 5️⃣ حفظ البيانات النهائية
# ----------------------------------------
df_final.to_csv("data/df_final.csv", index=False)
print("\nتم حفظ DataFrame النهائي في 'data/df_final.csv'")

FileNotFoundError: [Errno 2] No such file or directory: 'data/student-mat 2.csv'

In [ ]:
import pandas as pd
import requests
from sqlalchemy import create_engine
import os

try:
    df_csv = pd.read_csv("student-mat 2.csv")
    print("CSV الطلاب: ", df_csv.shape)
except Exception:
    print(" ملف CSV الطلاب غير موجود، سيتم تجاهله!")
    df_csv = pd.DataFrame()

try:
    df_excel = pd.read_excel("gestion.xlsx")
    print("Excel البيانات: ", df_excel.shape)
except Exception:
    print(" ملف Excel غير موجود أو خطأ في القراءة، سيتم تجاهله!")
    df_excel = pd.DataFrame()

try:
    df_movies = pd.read_csv("movies_metadata.csv", low_memory=False)
    df_movies.to_json("movies_metadata.json", orient="records")
    print("Movies CSV تم تحويله إلى JSON: movies_metadata.json")
except Exception:
    print(" ملف Movies CSV غير موجود أو خطأ في القراءة، سيتم تجاهله!")
    df_movies = pd.DataFrame()

try:
    engine = create_engine("mysql+pymysql://root:password@localhost/school")
    df_sql = pd.read_sql("SELECT * FROM etudiants", engine)
    print("SQL البيانات: ", df_sql.shape)
except Exception:
    print(" فشل الاتصال ب MySQL، سيتم تجاهلها!")
    df_sql = pd.DataFrame()

try:
    response = requests.get("https://jsonplaceholder.typicode.com/posts", timeout=10)
    response.raise_for_status()
    df_api = pd.DataFrame(response.json())
    print("API البيانات: ", df_api.shape)
except Exception:
    print(" فشل جلب بيانات API، سيتم تجاهله!")
    df_api = pd.DataFrame()

dfs = [df_csv, df_excel, df_movies, df_sql, df_api]
dfs_to_merge = [df for df in dfs if not df.empty]

if dfs_to_merge:
    df_final = pd.concat(dfs_to_merge, ignore_index=True, sort=False)
    print(" البيانات النهائية: ", df_final.shape)
    df_final.to_csv("final_dataset.csv", index=False)
    print(" تم حفظ الملف النهائي: final_dataset.csv")
else:
    print(" لا توجد بيانات للدمج!")

❌ ملف CSV الطلاب غير موجود، سيتم تجاهله!
❌ ملف Excel غير موجود أو خطأ في القراءة، سيتم تجاهله!
❌ ملف Movies CSV غير موجود أو خطأ في القراءة، سيتم تجاهله!
❌ فشل الاتصال ب MySQL، سيتم تجاهلها!
API البيانات:  (100, 4)
✅ البيانات النهائية:  (100, 4)
✅ تم حفظ الملف النهائي: final_dataset.csv